### ISSUE TITLE
WSL

### ISSUE THREAD

**Issue by MokatilDev** [vyfor/cord.nvim#292]
### Checklist

- [ x ]My problem isn't listed in the [Troubleshooting](https://github.com/vyfor/cord.nvim/wiki/Troubleshooting) section of the wiki
- [ x ] I have looked through [existing issues](https://github.com/vyfor/cord.nvim/issues)
- [ x ] I am aware of the recent [announcements](https://github.com/vyfor/cord.nvim/discussions/categories/announcements)

### Description

<img width="531" height="318" alt="Image" src="https://github.com/user-attachments/assets/13b41ddc-7a10-4801-b664-a7c7f93cea16" />

I have been read  https://github.com/vyfor/cord.nvim/wiki/Troubleshooting#-running-inside-wsl. but still doesn't work

### Checkhealth

```markdown
All OK
```

### Minimal configuration

```Lua
vim.env.LAZY_STDPATH = '.repro'
load(vim.fn.system 'curl -s https://raw.githubusercontent.com/folke/lazy.nvim/main/bootstrap.lua')()

require('lazy.minit').repro {
  spec = {
    {
      'vyfor/cord.nvim',
      build = ':Cord update',
    },
  },
}

-- do anything else you need to do to reproduce the issue
```

**Comment by MokatilDev** [comment]
<img width="671" height="339" alt="Image" src="https://github.com/user-attachments/assets/617ea66d-b27e-4da3-a803-99f1b654f825" />

**Comment by vyfor** [comment]
That's strange, could you try setting it to an absolute path instead? If it still fails, just send the config file for now.

**Comment by vyfor** [comment]
> redirect them to a file with `export CORD_LOG_FILE="./cord.log"`

I pushed a commit which should hopefully fix logging errors. Please retry the steps above and let me know if it works. And don't forget to enable trace logging:
```lua
opts = {
  log_level = vim.log.levels.TRACE,
},
```

**Comment by vyfor** [comment]
Oh looks like your previous issue was resolved actually. You now just have to get the relay working. Try using an absolute path this time:

```sh
nvim() {
    if ! pidof socat > /dev/null 2>&1; then
        [ -e /tmp/discord-ipc-0 ] && rm -f /tmp/discord-ipc-0
        socat UNIX-LISTEN:/tmp/discord-ipc-0,fork \
            EXEC:"/mnt/c/Users/USERNAME/Downloads/npiperelay.exe //./pipe/discord-ipc-0" 2>/dev/null &
    fi

    if [ $# -eq 0 ]; then
        command nvim
    else
        command nvim "$@"
    fi
}
```

Replace `c/Users/USERNAME/Downloads/npiperelay.exe` with wherever you put npiperelay on Windows.

**Comment by MokatilDev** [comment]
[cord.log](https://github.com/user-attachments/files/21867455/cord.log)

**Comment by vyfor** [comment]
> [cord.log](https://github.com/user-attachments/files/21867455/cord.log)

seems cut-off for some reason. either way, if it's still failing just run this and the issue should become clear

```sh
socat UNIX-LISTEN:/tmp/discord-ipc-0,fork EXEC:"/mnt/c/path/to/npiperelay.exe //./pipe/discord-ipc-0"
```

**Comment by MokatilDev** [comment]
2025/08/19 21:18:47 socat[366] E "/tmp/discord-ipc-0" exists

still doesn't work

**Comment by vyfor** [comment]
yeah i'm not really sure what's wrong, i'll let you know if i find any clues. in the meantime, it might speed things up if you're open to hopping on a call and sharing your screen: https://discord.gg/q9rC4bjCHv, no worries if not.
